"""remove product slug

Revision ID: 7876bb23adfe
Revises: 0bc04ab7feae
Create Date: 2026-09-30 16:11:12.123103

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7876bb23adfe'
down_revision = '0bc04ab7feae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.VARCHAR(length=220), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    # ### end Alembic commands ###
