"""add final amount and coupon code to orders

Revision ID: 8b0d4ce73684
Revises: 5e4ac2c125d1
Create Date: 2026-09-27 12:36:11.259848

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0d4ce73684'
down_revision = '5e4ac2c125d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'final_amount')
    # ### end Alembic commands ###
